const products = [
    {
        id: 1,
        name: "Limosine",
        url: require ('./Image/Deal1.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 2,
        name: "Limosine",
        url: require ('./Image/Deal2.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 3,
        name: "Limosine",
        url: require ('./Image/Deal3.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 4,
        name: "Limosine",
        url: require ('./Image/Deal4.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 5,
        name: "Limosine",
        url: require ('./Image/Deal5.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 6,
        name: "Limosine",
        url: require ('./Image/Deal6.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 7,
        name: "Limosine",
        url: require ('./Image/Deal7.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 8,
        name: "Limosine",
        url: require ('./Image/Deal8.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 9,
        name: "Limosine",
        url: require ('./Image/Deal9.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 10,
        name: "Limosine",
        url: require ('./Image/Deal10.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 11,
        name: "Limosine",
        url: require ('./Image/Deal11.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
    {
        id: 12,
        name: "Limosine",
        url: require ('./Image/Deal12.png'),
        category: "car",
        price: "$600",
        location: "Ikeja,Lagos",
    },
]

export default products;